version: "3"
services:
  service1:
    image: iilllii/demo:4.0
    ports:
      - "8888:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health | grep UP || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

